(function () {
  var LANG_KEY = 'eb-lang';

  var S = {
    tr: {
      'footer.back': '← Portfolyoya dön',
      'label.features': 'Özellikler',
      'label.tech': 'Teknoloji',
      'label.arch': 'Mimari',
      'label.how': 'Nasıl Çalışır',
      'label.tech-decisions': 'Teknik Kararlar',
      'label.numbers': 'Rakamlar',
      'label.results': 'Sonuçlar',

      // looked
      'looked.eyebrow': 'Mobil Uygulama · Yapay Zekâ',
      'looked.desc': 'Yapay zekâyı kişisel bir stil danışmanına dönüştüren uygulama. Fotoğraf yükle, anında kombin yorumu al; gardırobunu sisteme ekleyip AI\'nın ya da kendi oluşturduğun kombinleri keşfet.',
      'looked.status': 'Google Play & App Store\'da yayında',
      'looked.meta.date': '2026 / Aktif',
      'looked.cta.play': 'Google Play\'de gör',
      'looked.cta.store': 'App Store\'da gör',
      'looked.feat.1.title': 'Akıllı Gardırop Yönetimi',
      'looked.feat.1.desc': 'Gemini AI fotoğraftan kıyafeti tanıyıp otomatik etiketliyor. Arka plan kaldırma, kategori filtreleme, dijital katalog.',
      'looked.feat.2.title': 'AI Stil Danışmanlığı',
      'looked.feat.2.desc': 'Kombini yükle, 0-100 arası stil puanı ve profesyonel geri bildirim al. Gardırobundan otomatik kombin önerisi, uyum kontrolü.',
      'looked.feat.3.title': 'Kombin Takvimi',
      'looked.feat.3.desc': 'Gelecek günler için kıyafet planla. Geçmiş analizlerini ve kombinlerini istediğin zaman görüntüle.',
      'looked.feat.4.title': 'Çift Dil & Tema',
      'looked.feat.4.desc': 'Tüm arayüz ve AI yanıtları Türkçe/İngilizce. Terracotta-Sage-Champagne paletinde light & dark mod.',
      'looked.why.label': 'Neden Looked',
      'looked.why': 'Gardırop uygulamalarının çoğu düzenlemeye odaklanıyor: fotoğrafını çek, kategorile, arşivle. Ama asıl soru "bunu giysem mi?" sorusuna hiçbiri cevap vermiyor. Looked\'ın merkezinde bu var — kombini yükle, AI 0-100 arası somut bir stil puanı ve gerekçeli geri bildirim versin. Puanlama mekaniği aynı zamanda paylaşılabilir olacak şekilde tasarlandı; bir kişilik testi gibi organik olarak yayılma potansiyeli taşıyor.',
      'looked.tech.1.title': 'Firestore Güvenlik Kuralları',
      'looked.tech.1.desc': 'Güvenlik kuralları en baştan düşünülerek yazıldı: client tarafı bir kullanıcının kendini admin olarak işaretlemesi gibi yetki yükseltme senaryoları veri katmanında engellendi.',
      'looked.tech.2.title': 'Gerçek Ürün Gibi Yönetim',
      'looked.tech.2.desc': 'Yatırımcı dosyası ve düzenli versiyon raporlarıyla, tek kişilik bir yan proje değil gerçek bir ticari ürün disipliniyle geliştiriliyor.',
      'looked.stat.1': 'satır kod',
      'looked.stat.2': 'commit',
      'looked.stat.3': 'mağazada yayında',

      // rag
      'rag.eyebrow': 'Yapay Zekâ · RAG Sistemi',
      'rag.desc': 'Eğitime özelleştirilmiş RAG tabanlı akademik danışman. Intent-routing motoru her sorguyu SQL, vektör arama veya web taramasına yönlendirir. Bilmediğini açıkça söyler.',
      'rag.badge': 'Bitirme Projesi · 2025',
      'rag.meta.date': '2025 / Tamamlandı',
      'rag.cta': 'GitHub\'da gör',
      'rag.arch.1.desc': 'Soru tipini sınıflandırıp doğru modüle yönlendirir: SQL mi, RAG mi, web mi?',
      'rag.arch.2.desc': 'Doğal dil sorusunu SQL sorgusuna çevirir, üniversite veritabanından veri çeker.',
      'rag.arch.3.desc': 'PDF\'leri vektöre dönüştürür, ChromaDB\'de saklar, semantik arama yapar.',
      'rag.arch.4.desc': 'Güncel bilgi için istenilen web sitesini tarayan modül.',
      'rag.arch.5.desc': 'Konuşma bağlamını korur; önceki sorularla ilişki kurar.',
      'rag.arch.6.title': 'Token Takibi',
      'rag.arch.6.desc': 'Her konuşma için kullanılan token miktarını izler ve maliyet kontrolü sağlar.',
      'rag.tech.1.title': 'Native Function Calling',
      'rag.tech.1.desc': 'Orkestratör, LLM\'e serbest metin/JSON yazdırıp regex ile ayrıştırmak yerine OpenAI/Gemini\'nin gerçek <code>bind_tools</code>/<code>tool_calls</code> mekanizmasını kullanacak şekilde yeniden yazıldı; daha güvenilir ve daha az kırılgan bir araç çağırma katmanı.',
      'rag.tech.2.title': 'Kalıcı Konuşmalar',
      'rag.tech.2.desc': 'Konuşma geçmişi <code>conversations.db</code>\'de tutuluyor, sunucu yeniden başlatıldığında kaybolmuyor; session tabanlı bir login akışı eklendi.',
      'rag.tech.3.title': 'Belge Kapsamı',
      'rag.tech.3.desc': 'Her belge sohbete özel ya da global olarak işaretlenebiliyor; başta her belge her sohbete görünürken artık ayrı bir "Yüklü Dosyalar" ekranından kapsam yönetiliyor.',
      'rag.tech.4.title': 'RAGAS Değerlendirme Hattı',
      'rag.tech.4.desc': 'Mevcut pytest paketinden ayrı, opt-in bir <code>eval/</code> betiği; cevap kalitesini faithfulness, answer relevancy ve context precision/recall metrikleriyle ölçüyor.',
      'rag.stat.1': 'geçen pytest testi',
      'rag.stat.2': 'Text-SQL doğruluğu',
      'rag.stat.3': 'RAG doğruluğu',
      'rag.limit.title': 'Bilinen sınırlama:',
      'rag.limit.desc': 'RAGAS değerlendirmesi gerçek API\'ye karşı çalıştırıldı. Text-SQL sorguları 5/5 mükemmel skor aldı; RAG tarafında "bu belgenin 12. bölümü ne anlatıyor?" gibi yapısal/sıralı sorularda retrieval yanlış chunk getirdi (context recall 0.0) — saf semantik (embedding) aramanın "kaçıncı bölüm" tipi sorularda zayıf kaldığını gösteren somut bir bulgu.',
      'rag.feat.1.title': 'Çok Modlu Yanıt',
      'rag.feat.1.desc': 'Tek bir sistem içinde Text-SQL, Document RAG ve web crawler\'ı koordineli çalıştıran intent yönlendirme motoru.',
      'rag.feat.2.title': 'Vektör Tabanlı Arama',
      'rag.feat.2.desc': 'Üniversite PDF belgelerini ChromaDB\'ye gömerek semantik arama; sayfa ve kaynak referansıyla birlikte yanıt.',
      'rag.feat.3.title': 'Çok Turlu Sohbet',
      'rag.feat.3.desc': 'Konuşma geçmişini takip ederek bağlamı korur; "bu derse kayıt yaptırabilir miyim?" gibi bağlama dayalı soruları anlıyor.',
      'rag.feat.4.title': 'Dürüst Sınırlar',
      'rag.feat.4.desc': 'Bilmediği soruyu "bilmiyorum" diyerek geçiştirir; hallüsinasyon riskini minimize eden retrieval-first tasarım.',

      // optura
      'optura.eyebrow': 'Mobil · Yapay Zekâ · Flutter',
      'optura.desc': 'Kuzenimle kurduğumuz bir girişim: market fişini fotoğrafla, uygulama ürünleri tanıyıp ev erzağını otomatik olarak takip etsin. Son kullanma tarihini tahmin eder, bozulmak üzere olan ürünleri önceden bildirir ve dolaptaki malzemelere göre tarif önerir. Şu an TestFlight\'ta.',
      'optura.badge': 'Geliştirme Aşamasında',
      'optura.meta.date': '2025 / Devam ediyor',
      'optura.how.1.title': 'Fiş Tara',
      'optura.how.1.desc': 'Marketten aldıklarının fişini kameraya göster.',
      'optura.how.2.title': 'OCR + AI',
      'optura.how.2.desc': 'GPT-4o fişi okur, ürünleri tanır ve kategorize eder.',
      'optura.how.3.title': 'Erzak Listesi',
      'optura.how.3.desc': 'Ürünler dolabına eklenir, miktarlar takip edilir.',
      'optura.how.4.title': 'Akıllı Bildirim',
      'optura.how.4.desc': 'Son kullanma tarihi yaklaşan ürünler için push bildirimi.',
      'optura.feat.1.title': 'Fiş OCR',
      'optura.feat.1.desc': 'GPT-4o Vision ile market fişinden ürünleri otomatik tanıyıp pantriye ekler. Manuel giriş gerekmez.',
      'optura.feat.2.title': 'Son Kullanma Tahmini',
      'optura.feat.2.desc': 'Ürün kategorisine ve saklama koşullarına göre son kullanma tarihi tahmini; bozulmadan önce uyarır.',
      'optura.feat.3.title': 'AI Tarif Önerisi',
      'optura.feat.3.desc': 'Dolaptaki malzemelere bakıp yapılabilecek tarifleri öneriyor. Bitmek üzere olan malzemeleri önceliklendiriyor.',
      'optura.feat.4.title': 'Tüketim Analizi',
      'optura.feat.4.desc': 'Hangi ürünleri ne sıklıkla tükettiğini analiz ederek alışveriş planlamaya yardımcı olur.',
      'optura.tech.1.title': 'Kanonik Malzeme Eşleştirme',
      'optura.tech.1.desc': '"Domates", "Domates (1kg)", "domates salkım" gibi farklı fiş çıktılarını tek bir kanonik ürüne indirgeyen eşleştirme motoru; AI çıktısının tutarsızlığını veri modelinde çözüyor.',
      'optura.tech.2.title': '4 Katmanlı AI Doğrulama',
      'optura.tech.2.desc': 'GPT-4o\'nun fiş/tarif çıktıları, uygulamaya yansımadan önce art arda birden fazla mantık katmanından (format, birim dönüşümü, tutarlılık, güvenlik) geçiyor.',
      'optura.tech.3.title': 'Clean Architecture',
      'optura.tech.3.desc': 'Domain/data/presentation katmanlarına ayrılmış Flutter yapısı; Riverpod ile durum yönetimi, iş mantığı UI\'dan tamamen izole.',
      'optura.tech.4.title': 'İyimser Güncelleme (Optimistic UI)',
      'optura.tech.4.desc': 'Erzak listesi işlemleri anında arayüze yansır, sunucu hatasında otomatik geri alınır; beklemesiz bir kullanıcı deneyimi için.',
      'optura.tech.5.title': 'Ayrı Yönetim Paneli',
      'optura.tech.5.desc': 'Next.js ile yazılmış ayrı bir admin panel; ürün kategorileri, kanonik eşleştirme kuralları ve kullanıcı verisi mobil uygulamadan bağımsız yönetiliyor.',

      // jarvis
      'jarvis.eyebrow': 'Yapay Zekâ · Ses · Kişisel Proje',
      'jarvis.desc': 'Iron Man\'den ilham alan sesli kişisel asistan. "Jarvis" diyerek uyandır, soruyu sor; uygulama sesi metne çevirir, Gemini\'ye iletir, yanıtı sesli olarak geri sunar. Windows PC istemcisi ve React Native mobil uç.',
      'jarvis.badge': 'Aktif Geliştirme',
      'jarvis.cta': 'GitHub\'da gör',
      'jarvis.why.label': 'Farklılaşma',
      'jarvis.why': 'Açık kaynak sesli asistan projeleri genelde tek platforma odaklanıyor: ya sadece masaüstü ya sadece mobil. Jarvis\'te aynı FastAPI backend, WebSocket üzerinden hem Windows istemcisine hem React Native mobil uca hizmet veriyor — bu kombinasyon nadir görülüyor. Hobi/portfolyo projesi olduğu için önceliği büyüme değil, bulanık uyandırma eşleştirmesi ve follow-up modu gibi teknik detayların doğru çözülmesiydi.',
      'jarvis.how.1.title': 'Uyandırma',
      'jarvis.how.1.desc': '"Jarvis" uyandırma kelimesi bulanık eşleştirmeyle algılanır. Whisper transkripsiyonundaki tutarsızlıklara karşı dayanıklı.',
      'jarvis.how.2.title': 'Gemini + Function Calling',
      'jarvis.how.2.desc': 'Komut Gemini\'ye iletilir. Sistem kontrolü gerekiyorsa (uygulama aç, dosya oluştur) function-calling ile pyautogui/psutil tetiklenir.',
      'jarvis.how.3.title': 'Sesli Yanıt',
      'jarvis.how.3.desc': 'Yanıt TTS motoruyla seslendirilir. Follow-up modda uyandırma kelimesi gerektirmeden konuşma devam eder.',
      'jarvis.feat.1.title': 'Bulanık Uyandırma',
      'jarvis.feat.1.desc': 'Whisper "Jarvis" kelimesini her seferinde aynı şekilde transkribe etmez. Bulanık eşleştirme algoritması tutarsız sonuçları tolere eder.',
      'jarvis.feat.2.title': 'Follow-up Modu',
      'jarvis.feat.2.desc': 'Bir komut sonrasında kısa bir pencere boyunca uyandırma kelimesi gerekmez. Doğal diyalog akışını bozmaz.',
      'jarvis.feat.3.title': 'Sistem Kontrolü',
      'jarvis.feat.3.desc': 'Gemini function-calling üzerinden pyautogui ve psutil entegrasyonu. Uygulama açma, sistem bilgisi, hatırlatıcı gibi PC komutlarını çalıştırır.',
      'jarvis.feat.4.title': 'Çapraz Platform',
      'jarvis.feat.4.desc': 'WebSocket üzerinden konuşan Windows PC istemcisi ve React Native mobil uç. Aynı backend ikisine de hizmet verir.',

      // poco-loco
      'poco.eyebrow': 'Web · E-Ticaret',
      'poco.desc': 'Butik bir çanta markası için sıfırdan geliştirdiğim, canlı ödeme alan uçtan uca bir e-ticaret sitesi. Ürün kataloğu, sepet, iyzico ile ödeme, sipariş/kargo takibi, promosyon kodları ve bir yönetim paneli.',
      'poco.status': 'poco--loco.com\'da yayında',
      'poco.meta.date': '2026 / Yayında',
      'poco.cta': 'Siteye git',
      'poco.why.label': 'Neden Bu Proje',
      'poco.why': 'Butik bir çanta markası için sıfırdan kurulan bir e-ticaret sitesi; hazır bir altyapı (Shopify, Ticimax) değil, müşterinin ihtiyacına özel geliştirilen bir sistem. Gerçek para akışı olduğu için ödeme ve sipariş mantığının güvenilir olması kritikti: sunucu taraflı doğrulama, geri bildirim (callback) akışları ve indirim kodu kontrolleri hiçbir noktada istemciye güvenmeyecek şekilde kuruldu.',
      'poco.stat.1': 'haftalık geliştirme',
      'poco.stat.2': 'commit',
      'poco.stat.3': 'edge function',
      'poco.feat.1.title': 'Uçtan Uca Ödeme',
      'poco.feat.1.desc': 'iyzico entegrasyonu ile gerçek kart ödemesi; Supabase Edge Functions üzerinde çalışan sipariş oluşturma ve ödeme geri bildirim (callback) akışı.',
      'poco.feat.2.title': 'Sipariş & Kargo Takibi',
      'poco.feat.2.desc': 'Sipariş sonrası bildirim (e-posta), kargo durumu takibi ve promosyon kodu / indirim mantığı (kullanım limiti, son kullanma tarihi kontrolü).',
      'poco.feat.3.title': 'Yönetim Paneli',
      'poco.feat.3.desc': 'Ürün, sipariş ve içerik yönetimi için ayrı bir admin arayüzü.',
      'poco.feat.4.title': 'Çift Dil',
      'poco.feat.4.desc': 'i18next ile TR/EN arayüz desteği; form doğrulama zod şemalarıyla, react-hook-form üzerinden yönetiliyor.',
      'poco.arch.1.title': 'Supabase Edge Functions',
      'poco.arch.1.desc': 'create-order, iyzico-callback, send-order-notification, notify-contact gibi sunucu taraflı fonksiyonlarla ödeme ve bildirim mantığı istemciden ayrıştırıldı.',
      'poco.arch.2.title': 'Sunucu Taraflı Doğrulama',
      'poco.arch.2.desc': 'Sipariş tutarı ve indirim kodu geçerliliği ödeme adımında sunucuda yeniden hesaplanır; istemciden gelen fiyata hiçbir noktada güvenilmez.',
    },

    en: {
      'footer.back': '← Back to portfolio',
      'label.features': 'Features',
      'label.tech': 'Stack',
      'label.arch': 'Architecture',
      'label.how': 'How It Works',
      'label.tech-decisions': 'Technical Decisions',
      'label.numbers': 'By the Numbers',
      'label.results': 'Results',

      // looked
      'looked.eyebrow': 'Mobile App · AI',
      'looked.desc': 'Turns AI into a personal style consultant. Upload a photo for instant outfit feedback; add your wardrobe and discover outfits the AI — or you — create.',
      'looked.status': 'Live on Google Play & App Store',
      'looked.meta.date': '2026 / Active',
      'looked.cta.play': 'View on Google Play',
      'looked.cta.store': 'View on App Store',
      'looked.feat.1.title': 'Smart Wardrobe',
      'looked.feat.1.desc': 'Gemini AI detects clothing from photos and auto-tags them. Background removal, category filtering, digital catalog.',
      'looked.feat.2.title': 'AI Style Consulting',
      'looked.feat.2.desc': 'Upload an outfit, get a 0–100 style score and professional feedback. Automatic outfit suggestions from your wardrobe, compatibility check.',
      'looked.feat.3.title': 'Outfit Calendar',
      'looked.feat.3.desc': 'Plan outfits for upcoming days. View past analyses and combinations at any time.',
      'looked.feat.4.title': 'Bilingual & Themes',
      'looked.feat.4.desc': 'Full interface and AI responses in Turkish/English. Light & dark mode in terracotta-sage-champagne palette.',
      'looked.why.label': 'Why Looked',
      'looked.why': 'Most wardrobe apps focus on organization: photograph it, categorize it, archive it. None of them answer the actual question — "should I wear this?" That\'s what Looked is built around: upload an outfit, get a concrete 0-100 style score with reasoned feedback. The scoring mechanic was also designed to be shareable, with the organic spread potential of something like a personality quiz.',
      'looked.tech.1.title': 'Firestore Security Rules',
      'looked.tech.1.desc': 'Security rules were written with intent from day one: privilege-escalation scenarios like a client setting its own admin flag are blocked at the data layer.',
      'looked.tech.2.title': 'Run Like a Real Product',
      'looked.tech.2.desc': 'Managed with an investor deck and regular version reports — the discipline of an actual commercial product, not a solo side project.',
      'looked.stat.1': 'lines of code',
      'looked.stat.2': 'commits',
      'looked.stat.3': 'stores live',

      // rag
      'rag.eyebrow': 'AI · RAG System',
      'rag.desc': 'Education-focused RAG-based academic advisor. An intent-routing engine directs each query to SQL, vector search, or web crawl. Says clearly when it doesn\'t know.',
      'rag.badge': 'Graduation Project · 2025',
      'rag.meta.date': '2025 / Completed',
      'rag.cta': 'View on GitHub',
      'rag.arch.1.desc': 'Classifies the question type and routes it to the right module: SQL, RAG, or web.',
      'rag.arch.2.desc': 'Translates natural language questions into SQL to fetch data from the university database.',
      'rag.arch.3.desc': 'Converts PDFs to embeddings, stores in ChromaDB, performs semantic search.',
      'rag.arch.4.desc': 'A module that crawls the requested website for up-to-date information.',
      'rag.arch.5.desc': 'Preserves conversation context and relates to previous questions.',
      'rag.arch.6.title': 'Token Tracking',
      'rag.arch.6.desc': 'Tracks token usage per conversation and provides cost control.',
      'rag.tech.1.title': 'Native Function Calling',
      'rag.tech.1.desc': 'The orchestrator was rewritten to use OpenAI/Gemini\'s real <code>bind_tools</code>/<code>tool_calls</code> mechanism instead of having the LLM write free-text/JSON that gets parsed with regex — a more reliable, less brittle tool-calling layer.',
      'rag.tech.2.title': 'Persistent Conversations',
      'rag.tech.2.desc': 'Conversation history is kept in <code>conversations.db</code> and survives server restarts; a session-based login flow was added.',
      'rag.tech.3.title': 'Document Scope',
      'rag.tech.3.desc': 'Each document can be marked chat-specific or global; scope is now managed from a dedicated "Uploaded Files" screen instead of every document being visible to every chat.',
      'rag.tech.4.title': 'RAGAS Eval Harness',
      'rag.tech.4.desc': 'An opt-in <code>eval/</code> script, separate from the existing pytest suite, that measures answer quality via faithfulness, answer relevancy, and context precision/recall.',
      'rag.stat.1': 'pytest tests passing',
      'rag.stat.2': 'Text-SQL accuracy',
      'rag.stat.3': 'RAG accuracy',
      'rag.limit.title': 'Known limitation:',
      'rag.limit.desc': 'The RAGAS evaluation ran against the real API. Text-SQL queries scored a perfect 5/5; on the RAG side, structural/sequential questions like "what does section 12 of this document cover?" pulled the wrong chunk (context recall 0.0) — a concrete finding that pure semantic (embedding) search struggles with "which section" style questions.',
      'rag.feat.1.title': 'Multi-Mode Routing',
      'rag.feat.1.desc': 'Intent routing engine that coordinates Text-SQL, Document RAG, and web crawler within a single system.',
      'rag.feat.2.title': 'Vector Search',
      'rag.feat.2.desc': 'Embeds university PDFs into ChromaDB for semantic search; answers with page and source references.',
      'rag.feat.3.title': 'Multi-Turn Chat',
      'rag.feat.3.desc': 'Tracks conversation history to maintain context; understands context-dependent questions like "Can I register for this course?"',
      'rag.feat.4.title': 'Honest Limits',
      'rag.feat.4.desc': 'Responds with "I don\'t know" when it lacks information; retrieval-first design minimizes hallucination risk.',

      // optura
      'optura.eyebrow': 'Mobile · AI · Flutter',
      'optura.desc': 'A startup I co-founded with my cousin: photograph a grocery receipt and the app automatically identifies items and tracks your pantry. Estimates expiry dates, alerts before things go bad, and suggests recipes from what you have. Currently in TestFlight.',
      'optura.badge': 'In Development',
      'optura.meta.date': '2025 / Ongoing',
      'optura.how.1.title': 'Scan Receipt',
      'optura.how.1.desc': 'Point your camera at the grocery receipt.',
      'optura.how.2.title': 'OCR + AI',
      'optura.how.2.desc': 'GPT-4o reads the receipt, identifies items and categorizes them.',
      'optura.how.3.title': 'Pantry List',
      'optura.how.3.desc': 'Items are added to your pantry, quantities tracked.',
      'optura.how.4.title': 'Smart Alert',
      'optura.how.4.desc': 'Push notification for items approaching their expiry date.',
      'optura.feat.1.title': 'Receipt OCR',
      'optura.feat.1.desc': 'Automatically identifies items from grocery receipts using GPT-4o Vision and adds them to the pantry. No manual entry needed.',
      'optura.feat.2.title': 'Expiry Estimation',
      'optura.feat.2.desc': 'Estimates expiry dates based on product category and storage conditions; alerts before items go bad.',
      'optura.feat.3.title': 'AI Recipe Suggestions',
      'optura.feat.3.desc': 'Suggests recipes based on what\'s in your pantry. Prioritizes items running low or near expiry.',
      'optura.feat.4.title': 'Consumption Analysis',
      'optura.feat.4.desc': 'Analyzes which items you consume and how often to help with shopping planning.',
      'optura.tech.1.title': 'Canonical Item Matching',
      'optura.tech.1.desc': 'A matching engine that reduces receipt variants like "Tomato", "Tomato (1kg)", "cherry tomato" to a single canonical item; resolves AI output inconsistency at the data model level.',
      'optura.tech.2.title': '4-Layer AI Validation',
      'optura.tech.2.desc': 'GPT-4o\'s receipt/recipe outputs pass through multiple sequential logic layers (format, unit conversion, consistency, safety) before being applied.',
      'optura.tech.3.title': 'Clean Architecture',
      'optura.tech.3.desc': 'Flutter structure split into domain/data/presentation layers; Riverpod for state management, business logic fully isolated from UI.',
      'optura.tech.4.title': 'Optimistic UI',
      'optura.tech.4.desc': 'Pantry operations are reflected instantly in the UI and auto-reverted on server error; for a wait-free user experience.',
      'optura.tech.5.title': 'Separate Admin Panel',
      'optura.tech.5.desc': 'A separate admin panel built with Next.js; product categories, canonical matching rules, and user data are managed independently of the mobile app.',

      // jarvis
      'jarvis.eyebrow': 'AI · Voice · Personal Project',
      'jarvis.desc': 'Voice personal assistant inspired by Iron Man. Say "Jarvis" to wake it up, ask your question; the app converts speech to text, sends it to Gemini, and reads the response aloud. Windows PC client and React Native mobile app.',
      'jarvis.badge': 'Active Development',
      'jarvis.cta': 'View on GitHub',
      'jarvis.why.label': 'Differentiation',
      'jarvis.why': 'Open-source voice assistant projects usually target one platform: desktop-only or mobile-only. In Jarvis, the same FastAPI backend serves both a Windows client and a React Native mobile app over WebSocket — a combination that\'s rare to see. Since this is a hobby/portfolio project, the priority wasn\'t growth but getting details like fuzzy wake-word matching and follow-up mode genuinely right.',
      'jarvis.how.1.title': 'Wake Word',
      'jarvis.how.1.desc': 'The "Jarvis" wake word is detected with fuzzy matching. Resilient to Whisper transcription inconsistencies.',
      'jarvis.how.2.title': 'Gemini + Function Calling',
      'jarvis.how.2.desc': 'Command is sent to Gemini. If system control is needed (open app, create file), function-calling triggers pyautogui/psutil.',
      'jarvis.how.3.title': 'Voice Response',
      'jarvis.how.3.desc': 'Response is spoken via TTS. In follow-up mode, the conversation continues without needing the wake word again.',
      'jarvis.feat.1.title': 'Fuzzy Wake Detection',
      'jarvis.feat.1.desc': 'Whisper doesn\'t always transcribe "Jarvis" the same way. The fuzzy matching algorithm tolerates inconsistent results.',
      'jarvis.feat.2.title': 'Follow-up Mode',
      'jarvis.feat.2.desc': 'After a command, the wake word isn\'t needed for a short window. Doesn\'t disrupt natural dialogue flow.',
      'jarvis.feat.3.title': 'System Control',
      'jarvis.feat.3.desc': 'pyautogui and psutil integration via Gemini function-calling. Runs PC commands like opening apps, system info, reminders.',
      'jarvis.feat.4.title': 'Cross-Platform',
      'jarvis.feat.4.desc': 'Windows PC client and React Native mobile app communicating over WebSocket. The same backend serves both.',

      // poco-loco
      'poco.eyebrow': 'Web · E-Commerce',
      'poco.desc': 'End-to-end e-commerce site I built from scratch for a boutique bag brand, accepting live payments. Product catalog, cart, iyzico payments, order/shipping tracking, promo codes, and an admin panel.',
      'poco.status': 'Live at poco--loco.com',
      'poco.meta.date': '2026 / Live',
      'poco.cta': 'Visit Site',
      'poco.why.label': 'Why This Project',
      'poco.why': 'An e-commerce site built from scratch for a boutique bag brand — not on top of an off-the-shelf platform, but a system tailored to the client\'s needs. With real money moving through it, the payment and order logic had to be trustworthy: server-side validation, callback flows, and promo code checks were all built to never trust the client.',
      'poco.stat.1': 'weeks of development',
      'poco.stat.2': 'commits',
      'poco.stat.3': 'edge functions',
      'poco.feat.1.title': 'End-to-End Payments',
      'poco.feat.1.desc': 'Real card payment via iyzico integration; order creation and payment callback flow running on Supabase Edge Functions.',
      'poco.feat.2.title': 'Order & Shipping Tracking',
      'poco.feat.2.desc': 'Post-order email notifications, shipping status tracking, and promo code / discount logic (usage limits, expiry checks).',
      'poco.feat.3.title': 'Admin Panel',
      'poco.feat.3.desc': 'A separate admin interface for product, order, and content management.',
      'poco.feat.4.title': 'Bilingual',
      'poco.feat.4.desc': 'TR/EN interface support via i18next; form validation managed with Zod schemas through react-hook-form.',
      'poco.arch.1.title': 'Supabase Edge Functions',
      'poco.arch.1.desc': 'Server-side functions like create-order, iyzico-callback, send-order-notification, notify-contact separate payment and notification logic from the client.',
      'poco.arch.2.title': 'Server-Side Validation',
      'poco.arch.2.desc': 'Order totals and promo code validity are recalculated server-side at checkout; the price sent from the client is never trusted.',
    }
  };

  function applyLang(l) {
    var dict = S[l] || S.tr;
    document.documentElement.lang = l;
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (dict[key] != null) el.innerHTML = dict[key];
    });
    localStorage.setItem(LANG_KEY, l);
    document.querySelectorAll('.cs-lang-btn').forEach(function (b) {
      b.classList.toggle('active', b.dataset.lang === l);
    });
  }

  document.addEventListener('DOMContentLoaded', function () {
    var lang = localStorage.getItem(LANG_KEY) || 'en';
    applyLang(lang);
    document.querySelectorAll('.cs-lang-btn').forEach(function (b) {
      b.addEventListener('click', function () { applyLang(b.dataset.lang); });
    });
  });
})();
