/* ============================================================
   i18n dictionary — TR (default) / EN
   Usage: elements carry data-i18n="key"; text swapped on toggle.
   ============================================================ */
window.I18N = {
  tr: {
    "nav.about": "Hakkımda",
    "nav.skills": "Beceriler",
    "nav.work": "Başarılar",
    "nav.projects": "Projeler",
    "nav.path": "Deneyim",
    "nav.contact": "İletişim",
    "nav.cta": "İletişime geç",

    "hero.eyebrow": "Açık pozisyonlara bakıyorum",
    "hero.h1a": "Mobil ürünleri",
    "hero.h1c": "yayına taşıyorum.",
    "hero.sub": "React Native ile dört uygulama geliştirip Google Play'de yayınladım. Otonom drone yazılımıyla dünya birincisi oldum. Şimdi hem okuyor hem ürün geliştiriyorum.",
    "hero.cta1": "Projelere bak",
    "hero.cta2": "İletişime geç",
    "stat.apps": "Google Play'de yayında uygulama",
    "stat.world": "Otonom drone — dünya birinciliği",
    "stat.awards": "Yarışma derecesi (TÜBİTAK & uluslararası)",
    "stat.completed": "Tamamlanan proje",

    "about.idx": "01",
    "about.title": "Hakkımda",
    "about.lead": "Ben sadece kod yazan bir öğrenci değilim; <strong>fikri ürüne, ürünü de kullanıcıya</strong> dönüştürmeye çalışıyorum. Bir problemi görüp onu Play Store'da yayınlanan bir uygulamaya çevirmek beni motive ediyor.",
    "about.body": "Sakarya Üniversitesi'nde Bilgisayar Mühendisliği okurken bir yandan freelance mobil geliştirme yapıyorum. Geçmişte otonom drone yazılımlarıyla uğraştım, Romanya'da dünya birincisi oldum; şimdi odağım React Native ile hızlı ve kullanışlı mobil ürünler kurmak.",
    "meta.edu.k": "Eğitim",
    "meta.edu.v": "Bilgisayar Mühendisliği",
    "meta.edu.s": "Sakarya Üniversitesi",
    "meta.loc.k": "Konum",
    "meta.loc.v": "Türkiye",
    "meta.loc.s": "Uzaktan çalışmaya açık",
    "meta.lang.k": "Diller",
    "meta.lang.v": "Türkçe — anadil",
    "meta.lang.s": "İngilizce, İspanyolca",
    "meta.lic.k": "Lisans",
    "meta.lic.v": "İHA0 & İHA1",
    "meta.lic.s": "Drone pilotu lisansı",

    "skills.idx": "02",
    "skills.title": "Nasıl inşa ediyorum",
    "skills.m.title": "Mobil Geliştirme",
    "skills.ai.title": "Yapay Zeka & ML",
    "skills.tools.title": "Diğer Araçlar",

    "ach.idx": "03",
    "ach.title": "Başarılar",
    "ach.1.rank": "Dünya 1.'si",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romanya, 2022 — İki direk arasındaki kesikli çizgileri otonom takip eden drone yazılımıyla dünya birincisi olduk.",
    "ach.2.rank": "Türkiye 2.'si",
    "ach.2.title": "Teknofest İHA Yarışması",
    "ach.2.desc": "Liselerarası İnsansız Hava Araçları yarışmasında Türkiye ikinciliği kazandım.",
    "ach.3.rank": "Türkiye 3.'sü",
    "ach.3.title": "TÜBİTAK — Araç Çocuk Kilidi",
    "ach.3.desc": "Arabalarda çocuk kilitleri kontrolü projesiyle TÜBİTAK'ta Türkiye üçüncülüğü kazandım.",

    "proj.idx": "04",
    "proj.title": "Projeler",
    "proj.featured.tag": "Öne çıkan ürün",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "Yapay zekâyı kişisel bir stil danışmanına dönüştüren uygulama. Fotoğraf yükle, anında kombin yorumu al; gardırobunu sisteme ekleyip AI'nın ya da kendi oluşturduğun kombinleri keşfet. Firebase ve Google Sign-In ile veriler güvende.",
    "proj.featured.cta": "Google Play'de gör",
    "proj.live": "Yayında",
    "proj.status.progress": "Devam ediyor",
    "proj.status.done": "Tamamlandı",

    "proj.1.name": "Akıllı Danışman",
    "proj.1.desc": "Üniversite öğrencileri için yapay zekâ destekli danışman sistemi — veritabanını sorgular, belge analiz eder, bilmediğinde bunu açıkça söyler. Bitirme projem.",
    "proj.2.name": "WhatToDo",
    "proj.2.desc": "Görevlerini önceliğine göre sırala, günlerini önceden planla. Firebase ile bulutta güvenli, her cihazdan erişilebilir.",
    "proj.3.name": "Game Hub",
    "proj.3.desc": "XOX, Dama ve Satranç tek çatı altında — internetsiz oynanır. Yapay zekâya meydan oku ya da arkadaşınla aynı telefondan oyna.",
    "proj.4.name": "Periyodik Tablo",
    "proj.4.desc": "Elemente dokun; fotoğrafını, 3D Bohr modelini ve spektral çizgisini anında gör. Kuru bilgiyi keşfe çeviren bir öğrenme aracı.",
    "proj.5.name": "RoboChallenge AirRace",
    "proj.5.desc": "YOLO v8 ile iki direk arasındaki çizgileri takip eden otonom uçuş yazılımı — Romanya'da dünya birinciliği getirdi.",
    "proj.6.name": "Teknofest İHA",
    "proj.6.desc": "Pisti en hızlı tamamlama ve yük bırakma görevleri için tasarlanan, üretilen ve uçurulan otonom drone.",
    "proj.7.name": "TÜBİTAK — Akdoğan",
    "proj.7.desc": "Denizdeki drone şarj istasyonlarına, dalga enerjisini elektriğe çevirerek güç sağlayan sistem.",
    "proj.8.name": "TÜBİTAK — Deniz Kirliliği Tespiti",
    "proj.8.desc": "Su altı-su üstü entegre cihazla deniz suyundaki kirleticileri tespit eden, yapay zekâ destekli koruma sistemi.",
    "proj.9.name": "TÜBİTAK — DepMap",
    "proj.9.desc": "Deprem öncesi/sonrası görselleri kıyaslayıp kapanan yolları bulan, ekiplere en kısa rotayı çizen sistem.",
    "proj.10.name": "Teknofest Ulaşımda YZ",
    "proj.10.desc": "Havadan toplanan görüntülerle insan, araç ve iniş alanı tespiti; GPS arızası için görsel konumlama algoritmaları.",
    "proj.11.name": "TÜBİTAK — YZ Hız Sınırlayıcı",
    "proj.11.desc": "Trafik levhalarından hız limitini öğrenip aracın ECU'suna müdahale ederek limit aşımını önleyen sistem.",
    "proj.12.name": "Akıllı Çocuk Kilidi",
    "proj.12.desc": "Arka koltuktaki çocukları yüz tanıma ve ağırlık verisiyle tespit edip kilitleri otomatik kontrol eden sistem.",
    "proj.13.name": "Serum Yönetim Sistemi",
    "proj.13.desc": "Serum damla sayısını motorlarla kontrol eden, bitiş süresini hesaplayıp hemşireyi uyaran sistem.",
    "proj.cap": "ekran görüntüsü",
    "proj.more": "Tüm projeleri göster",
    "proj.less": "Daha az göster",

    "path.idx": "05",
    "path.title": "Deneyim & Eğitim",
    "path.1.kind": "İş",
    "path.1.role": "Freelance Mobil Geliştirici",
    "path.1.org": "Bağımsız",
    "path.1.when": "2025 — Şimdi",
    "path.1.desc": "React Native ile uçtan uca mobil uygulama geliştiriyorum; UI/UX tasarımından Firebase yönetimine kadar tüm süreç bende.",
    "path.2.kind": "Ürün",
    "path.2.role": "Geliştirici — Looked",
    "path.2.org": "Kişisel ürün",
    "path.2.when": "2024 — Şimdi",
    "path.2.desc": "AI destekli stil asistanını fikirden Google Play yayınına taşıdım.",
    "path.3.kind": "Yarışma",
    "path.3.role": "Otonom Drone Yazılım Ekibi",
    "path.3.org": "Uluslararası & TÜBİTAK",
    "path.3.when": "2019 — 2022",
    "path.3.desc": "Otonom uçuş algoritmaları geliştirdik; Romanya'da dünya birinciliği, Teknofest'te Türkiye ikinciliği ve TÜBİTAK derecesi kazandık.",
    "path.4.kind": "Eğitim",
    "path.4.role": "Bilgisayar Mühendisliği",
    "path.4.org": "Sakarya Üniversitesi",
    "path.4.when": "2022 — Devam Ediyor",
    "path.4.desc": "Lisans öğrenimim sürüyor; akademik ve proje bazlı çalışmalarla mühendislik becerilerimi geliştiriyorum.",

    "contact.idx": "06",
    "contact.title": "Yazın bana",
    "contact.lead": "Bir fikrin mi var, yoksa freelance bir iş mi? En hızlı yanıtı e-postadan alırsın.",
    "social.email": "E-posta",
    "social.email.copy": "Kopyalandı!",
    "social.linkedin": "LinkedIn",
    "social.github": "GitHub",
    "form.name": "İsim",
    "form.email": "E-posta",
    "form.msg": "Mesaj",
    "form.name.ph": "Adın",
    "form.email.ph": "seninadin@ornek.com",
    "form.msg.ph": "Projenden bahset…",
    "form.send": "Mesaj gönder",
    "form.sending": "Gönderiliyor…",
    "form.ok.title": "Teşekkürler!",
    "form.ok.body": "Mesajın alındı — en kısa sürede dönüş yapacağım.",
    "form.error": "Bir hata oluştu, lütfen daha sonra tekrar dene.",

    "mf.coda": "Hepsi aynı sorudan başladı.",
    "foot.tag": "Türkiye'den, kahveyle yapıldı.",
    "foot.top": "Yukarı çık"
  },

  en: {
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.work": "Wins",
    "nav.projects": "Projects",
    "nav.path": "Path",
    "nav.contact": "Contact",
    "nav.cta": "Get in touch",

    "hero.eyebrow": "Open to work",
    "hero.h1a": "I take mobile products",
    "hero.h1c": "to launch.",
    "hero.sub": "I've built four apps with React Native and shipped them on Google Play. I became world champion with autonomous drone software. Now I study and build products.",
    "hero.cta1": "See projects",
    "hero.cta2": "Get in touch",
    "stat.apps": "Apps live on Google Play",
    "stat.world": "Autonomous drone — world champion",
    "stat.awards": "Competition placements (TÜBİTAK & intl.)",
    "stat.completed": "Completed projects",

    "about.idx": "01",
    "about.title": "About",
    "about.lead": "I'm not just a student who writes code — I try to turn <strong>ideas into products, and products into something people use</strong>. Spotting a problem and shipping it as a real app on the Play Store is what drives me.",
    "about.body": "While studying Computer Engineering at Sakarya University, I do freelance mobile development on the side. I used to work on autonomous drone software and won first place in the world in Romania; today my focus is building fast, useful mobile products with React Native.",
    "meta.edu.k": "Education",
    "meta.edu.v": "Computer Engineering",
    "meta.edu.s": "Sakarya University",
    "meta.loc.k": "Location",
    "meta.loc.v": "Turkey",
    "meta.loc.s": "Open to remote work",
    "meta.lang.k": "Languages",
    "meta.lang.v": "Turkish — native",
    "meta.lang.s": "English, Spanish",
    "meta.lic.k": "License",
    "meta.lic.v": "UAV0 & UAV1",
    "meta.lic.s": "Licensed drone pilot",

    "skills.idx": "02",
    "skills.title": "How I build",
    "skills.m.title": "Mobile Development",
    "skills.ai.title": "AI & Machine Learning",
    "skills.tools.title": "Other Tools",

    "ach.idx": "03",
    "ach.title": "Wins",
    "ach.1.rank": "1st in World",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romania, 2022 — Took first place globally with autonomous drone software that follows dashed lines between two poles.",
    "ach.2.rank": "Turkey 2nd",
    "ach.2.title": "Teknofest UAV Competition",
    "ach.2.desc": "Placed 2nd in Turkey at the Inter-High School Unmanned Aerial Vehicles competition.",
    "ach.3.rank": "Turkey 3rd",
    "ach.3.title": "TÜBİTAK — Smart Child Lock",
    "ach.3.desc": "Won 3rd place in Turkey at TÜBİTAK with an automotive child-lock control project.",

    "proj.idx": "04",
    "proj.title": "Projects",
    "proj.featured.tag": "Featured product",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "An app that turns AI into a personal style consultant. Upload a photo for instant outfit feedback, add your wardrobe, and explore outfits the AI — or you — created. Data stays safe with Firebase and Google Sign-In.",
    "proj.featured.cta": "View on Google Play",
    "proj.live": "Live",
    "proj.status.progress": "In progress",
    "proj.status.done": "Completed",

    "proj.1.name": "Smart Academic Advisor",
    "proj.1.desc": "An AI-powered advisor for university students — queries the database, analyzes documents, and openly admits when it doesn't know. My graduation project.",
    "proj.2.name": "WhatToDo",
    "proj.2.desc": "Sort tasks by priority and plan your days ahead. Synced safely to the cloud with Firebase, accessible from any device.",
    "proj.3.name": "Game Hub",
    "proj.3.desc": "Tic-Tac-Toe, Checkers and Chess under one roof — playable offline. Challenge the AI or play with a friend on the same phone.",
    "proj.4.name": "Periodic Table",
    "proj.4.desc": "Tap an element to instantly see its photo, 3D Bohr model and spectral lines. Turns dry facts into something worth exploring.",
    "proj.5.name": "RoboChallenge AirRace",
    "proj.5.desc": "Autonomous flight software using YOLO v8 to follow lines between two poles — won us first place in the world in Romania.",
    "proj.6.name": "Teknofest UAV",
    "proj.6.desc": "Designed, built and flew an autonomous drone for fastest-lap and payload-drop competition tasks.",
    "proj.7.name": "TÜBİTAK — Akdoğan",
    "proj.7.desc": "A system that powers sea-based drone charging stations by converting wave kinetic energy into electricity.",
    "proj.8.name": "TÜBİTAK — Marine Pollution Detection",
    "proj.8.desc": "An AI-assisted underwater/surface device that detects pollutants in seawater to help protect marine ecosystems.",
    "proj.9.name": "TÜBİTAK — DepMap",
    "proj.9.desc": "Compares pre/post-earthquake imagery to find blocked roads and routes rescue teams along the shortest path.",
    "proj.10.name": "Teknofest Transportation AI",
    "proj.10.desc": "Detects people, vehicles and landing zones from aerial footage; visual positioning for GPS-failure scenarios.",
    "proj.11.name": "TÜBİTAK — AI Speed Limiter",
    "proj.11.desc": "Reads speed limits from traffic signs and intervenes in the vehicle's ECU to prevent exceeding them.",
    "proj.12.name": "Smart Child Lock",
    "proj.12.desc": "Detects children in the back seat via facial recognition and weight sensors, then auto-engages the door locks.",
    "proj.13.name": "IV Fluid Management",
    "proj.13.desc": "Controls IV drip rate with motors, calculates finish time, and alerts the nurse's station automatically.",
    "proj.cap": "screenshot",
    "proj.more": "Show all projects",
    "proj.less": "Show less",

    "path.idx": "05",
    "path.title": "Experience & Education",
    "path.1.kind": "Work",
    "path.1.role": "Freelance Mobile Developer",
    "path.1.org": "Independent",
    "path.1.when": "2025 — Now",
    "path.1.desc": "Building mobile apps end-to-end with React Native — from UI/UX design to managing the Firebase backend.",
    "path.2.kind": "Product",
    "path.2.role": "Developer — Looked",
    "path.2.org": "Personal product",
    "path.2.when": "2024 — Now",
    "path.2.desc": "Took an AI-powered style assistant from idea to a live Google Play release.",
    "path.3.kind": "Competition",
    "path.3.role": "Autonomous Drone Software Team",
    "path.3.org": "International & TÜBİTAK",
    "path.3.when": "2019 — 2022",
    "path.3.desc": "Built autonomous flight algorithms; won 1st in the world in Romania, 2nd in Turkey at Teknofest, and a TÜBİTAK placement.",
    "path.4.kind": "Education",
    "path.4.role": "Computer Engineering",
    "path.4.org": "Sakarya University",
    "path.4.when": "2022 — Ongoing",
    "path.4.desc": "Undergraduate studies — sharpening my engineering skills through coursework and hands-on projects.",

    "contact.idx": "06",
    "contact.title": "Drop me a line",
    "contact.lead": "Got an idea, or a freelance project in mind? Email gets the fastest reply.",
    "social.email": "Email",
    "social.email.copy": "Copied!",
    "social.linkedin": "LinkedIn",
    "social.github": "GitHub",
    "form.name": "Name",
    "form.email": "Email",
    "form.msg": "Message",
    "form.name.ph": "Your name",
    "form.email.ph": "you@example.com",
    "form.msg.ph": "Tell me about your project…",
    "form.send": "Send message",
    "form.sending": "Sending…",
    "form.ok.title": "Thank you!",
    "form.ok.body": "Your message has been received — I'll get back to you soon.",
    "form.error": "Something went wrong, please try again later.",

    "mf.coda": "It all started with one question.",
    "foot.tag": "Made with coffee, from Türkiye.",
    "foot.top": "Back to top"
  }
};
