/* ============================================================
   i18n dictionary - TR (default) / EN
   Usage: elements carry data-i18n="key"; text swapped on toggle.
   ============================================================ */
window.I18N = {
  tr: {
    "nav.about": "Hakkımda",
    "nav.skills": "Beceriler",
    "nav.work": "Projeler",
    "nav.awards": "Başarılar",
    "nav.projects": "Projeler",
    "nav.path": "Deneyim",
    "nav.contact": "İletişim",
    "nav.cta": "İletişime Geç <span class=\"arr\">→</span>",

    "hero.eyebrow": "EGEMEN BOZCA · GELİŞTİRİCİ",
    "hero.line1": "Proje \"tamam\" dendiği yerde,",
    "hero.line2": "ben <span class=\"accent\">devreye girerim.</span>",
    "hero.h1a": "Mobil ürünleri",
    "hero.h1c": "yayına taşıyorum.",
    "hero.h1": "Mobil ürünleri<br><span class=\"accent\">yayına taşıyorum.</span>",
    "hero.sub": "Mobil ve web alanında freelance çalışıyorum; asıl ilgi alanım yapay zekâ sistemleri. React Native ile dört uygulama yayınladım, RAG tabanlı AI danışman sistemi geliştirdim. Otonom drone yazılımıyla dünya birincisi oldum.",
    "hero.cta1": "İşleri Gör <span class=\"arr\">→</span>",
    "hero.cta2": "İletişim",
    "hero.m1": "4 uygulama yayında",
    "hero.m2": "Dünya Birincisi",
    "hero.m3": "Freelance'e açık",
    "stat.apps": "Google Play'de yayında uygulama",
    "stat.world": "Otonom drone, dünya birinciliği",
    "stat.awards": "Yarışma derecesi (TÜBİTAK & uluslararası)",
    "stat.completed": "Tamamlanan proje",

    "about.idx": "01",
    "about.title": "Hakkımda",
    "about.lead": "Tek bir alanda uzmanlaşmaktansa her alandan biraz bilgi sahibi olmayı tercih ederim. Gerçek hayattaki problemler tek bir alanla sınırlı kalmaz, benim bilgim de kalmıyor. Mobil uygulamalar, AI sistemleri, arayüz tasarımı: aralarında geziniyorum çünkü işler gerçekte böyle çözülüyor. Dar bir uzman problemin tek bir katmanını görür, bense hepsini görür ve daha ileriye taşırım.",
    "about.body": "Sakarya Üniversitesi Bilgisayar Mühendisliği mezunuyum. Mobil ve web alanında freelance çalışıyor, aynı zamanda yapay zekâ sistemleri üzerine projeler üretiyorum. Geçmişte otonom drone yazılımlarıyla uğraştım, Romanya'da dünya birincisi oldum; şimdi odağım AI destekli ürünler ve akıllı sistemler kurmak.",
    "meta.edu.k": "Eğitim",
    "meta.edu.v": "Bilgisayar Mühendisliği",
    "meta.edu.s": "Sakarya Üniversitesi · 2026",
    "meta.loc.k": "Konum",
    "meta.loc.v": "Türkiye",
    "meta.loc.s": "Uzaktan çalışmaya açık",
    "meta.lang.k": "Diller",
    "meta.lang.v": "Türkçe (anadil)",
    "meta.lang.s": "İngilizce, İspanyolca",
    "meta.lic.k": "Lisans",
    "meta.lic.v": "UAV0 & UAV1",
    "meta.lic.s": "Lisanslı drone pilotu",

    "skills.idx": "02",
    "skills.title": "Nasıl inşa ediyorum",
    "skills.m.title": "Mobil",
    "skills.ai.title": "AI / ML",
    "skills.tools.title": "Diğer Araçlar",

    "ach.idx": "03",
    "ach.title": "Başarılar",
    "ach.1.rank": "Dünya 1.'si",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romanya, 2022. 4 kişilik takımın tamamı yazılım üzerine çalıştı; hazır bir drone'u yarışma kurallarına uygun hale getirdik. Python ile yazdığımız kontrol yazılımı, iki direk arasındaki çizgiyi otonom takip ederek dünya birinciliğini getirdi.",
    "ach.2.rank": "Türkiye 2.'si",
    "ach.2.title": "Teknofest İHA Yarışması",
    "ach.2.desc": "Lise dönemi Teknofest İHA yarışmasında yaklaşık 10 kişilik takımın koordinasyonunu üstlendim, ana görevim ise otonom uçuş kontrol yazılımıydı. Türkiye genelinde 2. olduk.",
    "ach.3.rank": "Türkiye 3.'sü",
    "ach.3.title": "TÜBİTAK: Akıllı Çocuk Kilidi",
    "ach.3.desc": "9. sınıfta bir arkadaşımla geliştirdiğimiz TÜBİTAK 2204 projesi. Arkaya bakan bir kamera, arka koltukta gerçekten çocuk olup olmadığını tespit ediyordu; örneğin sağda çocuk solda yetişkin varsa sistem sadece sağ kapıyı kilitliyordu. Türkiye 3.'sü olduk.",

    "proj.idx": "04",
    "proj.title": "Projeler",
    "proj.featured.tag": "Öne çıkarılan ürün",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "AI destekli kişisel stil asistanı. Fotoğraf yükle, anında kombin yorumu al; gardırobunu ekle ve AI ile kombin keşfet.",
    "proj.featured.cta": "Google Play",
    "proj.featured.cta.ios": "App Store",
    "proj.cs": "Case study <span class=\"arr\">→</span>",
    "proj.cs.link": "Case study →",
    "proj.featured.f1.title": "Akıllı Gardırop",
    "proj.featured.f1.desc": "Gemini AI fotoğraftan kıyafeti tanıyıp otomatik etiketliyor. Arka plan kaldırma, kategori filtreleme, dijital katalog.",
    "proj.featured.f2.title": "AI Stil Danışmanlığı",
    "proj.featured.f2.desc": "Kombini yükle, 0-100 stil puanı ve profesyonel geri bildirim al. Gardırobundan otomatik kombin önerisi.",
    "proj.featured.f3.title": "Kombin Takvimi",
    "proj.featured.f3.desc": "Gelecek günler için kıyafet planla. Geçmiş analizlerini ve kombinlerini istediğin zaman görüntüle.",
    "proj.featured.f4.title": "Dijital Gardırop",
    "proj.featured.f4.desc": "Tüm kıyafetlerin kategoriye göre düzenli. Items, Outfits ve Insights sekmeleriyle tek yerden yönet.",
    "fan.tab.0": "Ana Sayfa",
    "fan.tab.1": "AI Stil Analizi",
    "fan.tab.2": "Dijital Gardrop",
    "proj.live": "Yayında",
    "proj.status.progress": "Devam ediyor",
    "proj.status.done": "Tamamlandı · Bitirme Projesi",
    "rag.tip.0": "Sorgu türüne göre SQL, RAG veya web taramasına yönlendirir",
    "rag.tip.1": "PDF → ChromaDB embedding → semantik arama",
    "rag.tip.2": "Güncel bilgi için üniversite sitesini tarar",
    "rag.tip.3": "Konuşma bağlamını sorgular arasında korur",
    "rag.tip.4": "Her konuşma için token kullanımını takip eder",

    "proj.1.name": "AkademikChatbot",
    "proj.1.desc": "Eğitim odaklı RAG tabanlı akademik danışman. Bir intent-routing motoru her sorguyu SQL, vektör araması veya web taramasına yönlendirir. Teknik olarak bu portföyün en karmaşık projesi.",
    "proj.1.type": "Python · RAG",
    "proj.1.cta": "GitHub <span class=\"arr\">→</span>",
    "proj.2.name": "Jarvis",
    "proj.2.desc": "Iron Man'den ilham alan sesli asistan. \"Jarvis\" uyandırma kelimesi Gemini + function-calling ile PC kontrolü sağlar.",
    "proj.2.type": "AI · Ses · Python",
    "proj.3.name": "Optura",
    "proj.3.desc": "Market fişini fotoğrafla, uygulama erzağını otomatik takip eder: son kullanma tahmini yapar, elindeki malzemelere göre tarif önerir.",
    "proj.3.type": "Mobil · AI · Flutter",
    "proj.4.name": "Poco Loco",
    "proj.4.desc": "Butik bir çanta markası için uçtan uca e-ticaret. iyzico ile canlı ödeme, sipariş takibi, yönetim paneli. 240+ commit.",
    "proj.4.type": "Web · E-Ticaret",

    "path.idx": "05",
    "path.title": "Deneyim",
    "path.1.kind": "İş",
    "path.1.role": "Freelance Mobil Geliştirici",
    "path.1.org": "Bağımsız",
    "path.1.when": "2025 / Şimdi",
    "path.1.desc": "Web ve mobil projeler geliştiriyorum; UI/UX tasarımından backend entegrasyonuna kadar tüm süreç bende.",
    "path.2.kind": "Ürün",
    "path.2.role": "Geliştirici, Looked",
    "path.2.org": "Kişisel",
    "path.2.when": "2026 / Şimdi",
    "path.2.desc": "AI destekli stil asistanını fikirden Google Play yayınına taşıdım.",
    "path.3.kind": "Yarışma",
    "path.3.role": "Otonom Drone Takımı",
    "path.3.org": "Uluslararası & TÜBİTAK",
    "path.3.when": "2019 / 2022",
    "path.3.desc": "Otonom uçuş algoritmaları geliştirdik; Romanya'da dünya birinciliği, Teknofest'te Türkiye ikinciliği ve TÜBİTAK derecesi kazandık.",
    "contact.idx": "06",
    "contact.title": "Bana yazın",
    "contact.lead": "Bir fikrin ya da freelance projen mi var? E-posta en hızlı cevabı alır.",
    "social.email": "E-posta",
    "social.email.copy": "Kopyalandı!",
    "social.linkedin": "LinkedIn",
    "social.upwork": "Upwork",
    "social.github": "GitHub",
    "form.name": "İsim",
    "form.email": "E-posta",
    "form.msg": "Mesaj",
    "form.name.label": "Ad",
    "form.email.label": "E-posta",
    "form.msg.label": "Mesaj",
    "form.name.ph": "Adın",
    "form.email.ph": "seninadin@ornek.com",
    "form.msg.ph": "Projenden bahset…",
    "form.send": "Mesaj gönder <span class=\"arr\">→</span>",
    "form.sending": "Gönderiliyor…",
    "form.ok.title": "Teşekkürler!",
    "form.ok.body": "Mesajın alındı. En kısa sürede dönüş yapacağım.",
    "form.error": "Lütfen tüm alanları doldurun.",
    "form.success.title": "Mesaj gönderildi!",
    "form.success.body": "En kısa sürede dönüş yapacağım.",
    "footer.top": "↑ Başa dön",

    "mf.line1": "4 uygulama.",
    "mf.line2": "1 dünya birinciliği.",
    "mf.line3": "Sayısız commit.",
    "mf.coda": "Hepsi aynı sorudan başladı.",
    "foot.tag": "Türkiye'den, kahveyle yapıldı.",
    "foot.top": "Yukarı çık",

    "mq.rn": "React Native",
    "mq.ai": "AI Entegrasyonu",
    "mq.rag": "RAG Sistemleri",
    "mq.drone": "Drone Yazılımı"
  },

  en: {
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.work": "Projects",
    "nav.awards": "Awards",
    "nav.projects": "Projects",
    "nav.path": "Experience",
    "nav.contact": "Contact",
    "nav.cta": "Get in touch <span class=\"arr\">→</span>",

    "hero.eyebrow": "EGEMEN BOZCA · DEVELOPER",
    "hero.line1": "Good enough",
    "hero.line2": "isn't <span class=\"accent\">good enough.</span>",
    "hero.h1": "I build mobile apps<br><span class=\"accent\">people actually use.</span>",
    "hero.h1a": "I take mobile products",
    "hero.h1c": "to launch.",
    "hero.sub": "React Native developer based in Turkey. I've shipped 4 apps to the Play Store and App Store, built AI-powered systems, and I'm open to new projects.",
    "hero.cta1": "View Work <span class=\"arr\">→</span>",
    "hero.cta2": "Contact",
    "hero.m1": "4 apps live",
    "hero.m2": "World Champion",
    "hero.m3": "Open to freelance",
    "hero.caption": "4 apps live on Play Store · Open to projects",
    "stat.apps": "Apps on Play Store",
    "stat.years": "Years of experience",
    "stat.world": "Autonomous drone, world champion",
    "stat.awards": "Competition awards",
    "stat.projects": "Projects shipped",
    "stat.completed": "Completed projects",

    "about.idx": "01",
    "about.title": "About",
    "about.lead": "I'd rather know a bit about everything than everything about one thing. Real-world problems don't stay inside a single field, so my skill set doesn't either. Mobile apps, AI systems, interface design: I move between them because that's how the work actually gets solved. A narrow specialist sees one layer of a problem. I see all of them, and take it further.",
    "about.body": "I recently graduated with a Computer Engineering degree from Sakarya University. I freelance in mobile and web, while building projects around AI systems. I used to work on autonomous drone software and won first place in the world in Romania; now my focus is AI-powered products and intelligent systems.",
    "meta.edu.k": "Education",
    "meta.edu.v": "Computer Engineering",
    "meta.edu.s": "Sakarya University · 2026",
    "meta.loc.k": "Location",
    "meta.loc.v": "Turkey",
    "meta.loc.s": "Open to remote work",
    "meta.lang.k": "Languages",
    "meta.lang.v": "Turkish (native)",
    "meta.lang.s": "English, Spanish",
    "meta.lic.k": "License",
    "meta.lic.v": "UAV0 & UAV1",
    "meta.lic.s": "Licensed drone pilot",

    "skills.idx": "02",
    "skills.title": "How I build",
    "skills.m.title": "Mobile",
    "skills.ai.title": "AI / ML",
    "skills.tools.title": "Other Tools",

    "ach.idx": "03",
    "ach.title": "Awards",
    "ach.1.rank": "1st in World",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romania, 2022. Our four-person team worked entirely on software, adapting an off-the-shelf drone to the competition's rules. The control software we wrote in Python autonomously tracked the line between two poles, taking first place in the world.",
    "ach.2.rank": "Turkey 2nd",
    "ach.2.title": "Teknofest UAV Competition",
    "ach.2.desc": "During high school, I coordinated our ~10-person team for the Teknofest UAV competition while owning autonomous flight control as my main task. Placed 2nd nationally.",
    "ach.3.rank": "Turkey 3rd",
    "ach.3.title": "TÜBİTAK: Smart Child Lock",
    "ach.3.desc": "A TÜBİTAK 2204 project I built with a friend in 9th grade. A rear-facing camera detected whether a child was actually present in the back seat, locking only the relevant door: if a child sat on the right and an adult on the left, only the right door locked. Placed 3rd nationally.",

    "proj.idx": "04",
    "proj.title": "Projects",
    "proj.featured.tag": "Featured product",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "AI-powered personal style assistant. Upload a photo, get instant outfit feedback; add your wardrobe and discover outfit combinations.",
    "proj.featured.cta": "Google Play",
    "proj.featured.cta.ios": "App Store",
    "proj.cs": "Case study <span class=\"arr\">→</span>",
    "proj.cs.link": "Case study →",
    "proj.featured.f1.title": "Smart Wardrobe",
    "proj.featured.f1.desc": "Gemini AI detects clothing from photos and auto-tags them. Background removal, category filtering, digital catalog.",
    "proj.featured.f2.title": "AI Style Consulting",
    "proj.featured.f2.desc": "Upload an outfit, get a 0–100 style score and professional feedback. Automatic suggestions from your wardrobe.",
    "proj.featured.f3.title": "Outfit Calendar",
    "proj.featured.f3.desc": "Plan outfits for upcoming days. View past analyses and combinations at any time.",
    "proj.featured.f4.title": "Digital Catalog",
    "proj.featured.f4.desc": "All your clothes organized by category. Browse items, outfits and insights in one place.",
    "fan.tab.0": "Home",
    "fan.tab.1": "AI Style Analysis",
    "fan.tab.2": "Digital Wardrobe",
    "proj.live": "Live",
    "proj.status.progress": "In progress",
    "proj.status.done": "Completed · Graduation Project",
    "rag.tip.0": "Routes to SQL, RAG, or web based on query type",
    "rag.tip.1": "PDF → ChromaDB embeddings → semantic search",
    "rag.tip.2": "Crawls university site for up-to-date info",
    "rag.tip.3": "Preserves context across turns",
    "rag.tip.4": "Tracks token usage per conversation",

    "proj.1.name": "AkademikChatbot",
    "proj.1.desc": "Education-focused RAG-based academic advisor. An intent-routing engine directs each query to SQL, vector search, or web crawl. Technically the most complex project in this portfolio.",
    "proj.1.type": "Python · RAG",
    "proj.1.cta": "GitHub <span class=\"arr\">→</span>",
    "proj.2.name": "Jarvis",
    "proj.2.desc": "Iron Man-inspired voice assistant. \"Jarvis\" wake word triggers Gemini + function-calling for PC control. Whisper STT + TTS response.",
    "proj.2.type": "AI · Voice · Python",
    "proj.3.name": "Optura",
    "proj.3.desc": "Photograph a grocery receipt and the app auto-tracks your pantry: estimates expiry dates, suggests recipes based on what you have.",
    "proj.3.type": "Mobile · AI · Flutter",
    "proj.4.name": "Poco Loco",
    "proj.4.desc": "End-to-end e-commerce for a boutique bag brand. Live payments via iyzico, order tracking, admin panel. 240+ commits.",
    "proj.4.type": "Web · E-Commerce",

    "path.idx": "05",
    "path.title": "Experience",
    "path.1.kind": "Work",
    "path.1.role": "Freelance Mobile Dev",
    "path.1.org": "Independent",
    "path.1.when": "2025 / Now",
    "path.1.desc": "Building web and mobile projects end-to-end, from UI/UX design to backend integration.",
    "path.2.kind": "Product",
    "path.2.role": "Dev, Looked",
    "path.2.org": "Personal",
    "path.2.when": "2026 / Now",
    "path.2.desc": "Took an AI-powered style assistant from idea to a live Google Play release.",
    "path.3.kind": "Competition",
    "path.3.role": "Autonomous Drone Team",
    "path.3.org": "International & TÜBİTAK",
    "path.3.when": "2019 / 2022",
    "path.3.desc": "Built autonomous flight algorithms; won 1st in the world in Romania, 2nd in Turkey at Teknofest, and a TÜBİTAK placement.",
    "contact.idx": "06",
    "contact.title": "Drop me a line",
    "contact.lead": "Got an idea, or a freelance project in mind? Email gets the fastest reply.",
    "social.email": "Email",
    "social.email.copy": "Copied!",
    "social.linkedin": "LinkedIn",
    "social.upwork": "Upwork",
    "social.github": "GitHub",
    "form.name": "Name",
    "form.email": "Email",
    "form.msg": "Message",
    "form.name.label": "Name",
    "form.email.label": "Email",
    "form.msg.label": "Message",
    "form.name.ph": "Your name",
    "form.email.ph": "you@example.com",
    "form.msg.ph": "Tell me about your project…",
    "form.send": "Send message <span class=\"arr\">→</span>",
    "form.sending": "Sending…",
    "form.ok.title": "Thank you!",
    "form.ok.body": "Your message has been received. I'll get back to you soon.",
    "form.error": "Please fill in all fields.",
    "form.success.title": "Message sent!",
    "form.success.body": "I'll get back to you as soon as possible.",
    "footer.top": "↑ Back to top",

    "mf.line1": "4 apps.",
    "mf.line2": "1 world championship.",
    "mf.line3": "Countless commits.",
    "mf.coda": "It all started with one question.",
    "foot.tag": "Made with coffee, from Türkiye.",
    "foot.top": "Back to top",

    "mq.rn": "React Native",
    "mq.ai": "AI Integration",
    "mq.rag": "RAG Systems",
    "mq.drone": "Drone Software"
  }
};
