/* ============================================================
   i18n dictionary — TR (default) / EN
   Usage: elements carry data-i18n="key"; text swapped on toggle.
   ============================================================ */
window.I18N = {
  tr: {
    "nav.about": "Hakkımda",
    "nav.skills": "Beceriler",
    "nav.work": "Başarılar",
    "nav.projects": "Projeler",
    "nav.path": "Deneyim",
    "nav.contact": "İletişim",
    "nav.cta": "İletişime geç",

    "hero.eyebrow": "Açık pozisyonlara bakıyorum",
    "hero.h1a": "Mobil ürünleri",
    "hero.h1c": "yayına taşıyorum.",
    "hero.sub": "Mobil ve web alanında freelance çalışıyorum; asıl ilgi alanım yapay zekâ sistemleri. React Native ile dört uygulama yayınladım, RAG tabanlı AI danışman sistemi geliştirdim. Otonom drone yazılımıyla dünya birincisi oldum.",
    "hero.cta1": "Projelere bak",
    "hero.cta2": "İletişime geç",
    "stat.apps": "Google Play'de yayında uygulama",
    "stat.world": "Otonom drone — dünya birinciliği",
    "stat.awards": "Yarışma derecesi (TÜBİTAK & uluslararası)",
    "stat.completed": "Tamamlanan proje",

    "about.idx": "01",
    "about.title": "Hakkımda",
    "about.lead": "Ben sadece kod yazan biri değilim; mobil ve web projeler üretirken <strong>asıl ilgim yapay zekâ sistemleri</strong> — LLM entegrasyonlarından RAG mimarilerine kadar. Bir fikri çalışan bir sisteme dönüştürmek beni motive ediyor.",
    "about.body": "Sakarya Üniversitesi Bilgisayar Mühendisliği mezunuyum. Mobil ve web alanında freelance çalışıyor, aynı zamanda yapay zekâ sistemleri üzerine projeler üretiyorum. Geçmişte otonom drone yazılımlarıyla uğraştım, Romanya'da dünya birincisi oldum; şimdi odağım AI destekli ürünler ve akıllı sistemler kurmak.",
    "meta.edu.k": "Eğitim",
    "meta.edu.v": "Bilgisayar Mühendisliği",
    "meta.edu.s": "Sakarya Üniversitesi · 2026",
    "meta.loc.k": "Konum",
    "meta.loc.v": "Türkiye",
    "meta.loc.s": "Uzaktan çalışmaya açık",
    "meta.lang.k": "Diller",
    "meta.lang.v": "Türkçe — anadil",
    "meta.lang.s": "İngilizce, İspanyolca",
    "meta.lic.k": "Lisans",
    "meta.lic.v": "İHA0 & İHA1",
    "meta.lic.s": "Drone pilotu lisansı",

    "skills.idx": "02",
    "skills.title": "Nasıl inşa ediyorum",
    "skills.m.title": "Mobil Geliştirme",
    "skills.ai.title": "Yapay Zeka & ML",
    "skills.tools.title": "Diğer Araçlar",

    "ach.idx": "03",
    "ach.title": "Başarılar",
    "ach.1.rank": "Dünya 1.'si",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romanya, 2022 — İki direk arasındaki kesikli çizgileri otonom takip eden drone yazılımıyla dünya birincisi olduk.",
    "ach.2.rank": "Türkiye 2.'si",
    "ach.2.title": "Teknofest İHA Yarışması",
    "ach.2.desc": "Liselerarası İnsansız Hava Araçları yarışmasında Türkiye ikinciliği kazandım.",
    "ach.3.rank": "Türkiye 3.'sü",
    "ach.3.title": "TÜBİTAK — Araç Çocuk Kilidi",
    "ach.3.desc": "Arabalarda çocuk kilitleri kontrolü projesiyle TÜBİTAK'ta Türkiye üçüncülüğü kazandım.",

    "proj.idx": "04",
    "proj.title": "Projeler",
    "proj.featured.tag": "Öne çıkan ürün",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "Yapay zekâyı kişisel bir stil danışmanına dönüştüren uygulama. Fotoğraf yükle, anında kombin yorumu al; gardırobunu sisteme ekleyip AI'nın ya da kendi oluşturduğun kombinleri keşfet. Firebase ve Google Sign-In ile veriler güvende.",
    "proj.featured.cta": "Google Play'de gör",
    "proj.featured.cta.ios": "App Store'da gör",
    "proj.live": "Yayında",
    "proj.status.progress": "Devam ediyor",
    "proj.status.done": "Tamamlandı",

    "proj.1.name": "Akıllı Danışman",
    "proj.1.desc": "Üniversite öğrencileri için yapay zekâ destekli danışman sistemi — veritabanını sorgular, belge analiz eder, bilmediğinde bunu açıkça söyler. Bitirme projem.",
    "proj.1.type": "Yapay Zekâ",
    "proj.2.name": "Poco Loco",
    "proj.2.desc": "İfade özgürlüğü temalı bir çanta markası için sıfırdan tasarlayıp kodladığım e-ticaret sitesi — ürün kataloğu, sepet, favoriler ve giriş sistemiyle uçtan uca bir mağaza deneyimi.",
    "proj.2.type": "Web · E-Ticaret",
    "proj.3.name": "Optura",
    "proj.3.desc": "Market fişlerinden ürünleri tanıyıp ev erzakını otomatik takip eden uygulama; son kullanma tarihlerini tahmin ederek bozulmaya başlayan ürünleri önceden haber veriyor. Şu an geliştirme aşamasında.",
    "proj.3.type": "Mobil · AI",

    "path.idx": "05",
    "path.title": "Deneyim",
    "path.1.kind": "İş",
    "path.1.role": "Freelance Web & Mobil Geliştirici",
    "path.1.org": "Bağımsız",
    "path.1.when": "2025 — Şimdi",
    "path.1.desc": "Web ve mobil projeler geliştiriyorum; UI/UX tasarımından backend entegrasyonuna kadar tüm süreç bende.",
    "path.2.kind": "Ürün",
    "path.2.role": "Geliştirici — Looked",
    "path.2.org": "Kişisel ürün",
    "path.2.when": "2026 — Şimdi",
    "path.2.desc": "AI destekli stil asistanını fikirden Google Play yayınına taşıdım.",
    "path.3.kind": "Yarışma",
    "path.3.role": "Otonom Drone Yazılım Ekibi",
    "path.3.org": "Uluslararası & TÜBİTAK",
    "path.3.when": "2019 — 2022",
    "path.3.desc": "Otonom uçuş algoritmaları geliştirdik; Romanya'da dünya birinciliği, Teknofest'te Türkiye ikinciliği ve TÜBİTAK derecesi kazandık.",
    "contact.idx": "06",
    "contact.title": "Yazın bana",
    "contact.lead": "Bir fikrin mi var, yoksa freelance bir iş mi? En hızlı yanıtı e-postadan alırsın.",
    "social.email": "E-posta",
    "social.email.copy": "Kopyalandı!",
    "social.linkedin": "LinkedIn",
    "social.github": "GitHub",
    "form.name": "İsim",
    "form.email": "E-posta",
    "form.msg": "Mesaj",
    "form.name.ph": "Adın",
    "form.email.ph": "seninadin@ornek.com",
    "form.msg.ph": "Projenden bahset…",
    "form.send": "Mesaj gönder",
    "form.sending": "Gönderiliyor…",
    "form.ok.title": "Teşekkürler!",
    "form.ok.body": "Mesajın alındı — en kısa sürede dönüş yapacağım.",
    "form.error": "Bir hata oluştu, lütfen daha sonra tekrar dene.",

    "mf.line1": "4 uygulama.",
    "mf.line2": "1 dünya birinciliği.",
    "mf.line3": "Sayısız commit.",
    "mf.coda": "Hepsi aynı sorudan başladı.",
    "foot.tag": "Türkiye'den, kahveyle yapıldı.",
    "foot.top": "Yukarı çık"
  },

  en: {
    "nav.about": "About",
    "nav.skills": "Skills",
    "nav.work": "Wins",
    "nav.projects": "Projects",
    "nav.path": "Path",
    "nav.contact": "Contact",
    "nav.cta": "Get in touch",

    "hero.eyebrow": "Open to work",
    "hero.h1a": "I take mobile products",
    "hero.h1c": "to launch.",
    "hero.sub": "I freelance in mobile and web; my real focus is AI systems. I've shipped four apps with React Native, built a RAG-powered AI advisor, and won a world championship with autonomous drone software.",
    "hero.cta1": "See projects",
    "hero.cta2": "Get in touch",
    "stat.apps": "Apps live on Google Play",
    "stat.world": "Autonomous drone — world champion",
    "stat.awards": "Competition placements (TÜBİTAK & intl.)",
    "stat.completed": "Completed projects",

    "about.idx": "01",
    "about.title": "About",
    "about.lead": "I'm not just someone who writes code — while I build mobile and web products, my real interest is <strong>AI systems</strong>: from LLM integrations to RAG architectures. Turning an idea into a working system is what drives me.",
    "about.body": "I recently graduated with a Computer Engineering degree from Sakarya University. I freelance in mobile and web, while building projects around AI systems. I used to work on autonomous drone software and won first place in the world in Romania; now my focus is AI-powered products and intelligent systems.",
    "meta.edu.k": "Education",
    "meta.edu.v": "Computer Engineering",
    "meta.edu.s": "Sakarya University · 2026",
    "meta.loc.k": "Location",
    "meta.loc.v": "Turkey",
    "meta.loc.s": "Open to remote work",
    "meta.lang.k": "Languages",
    "meta.lang.v": "Turkish — native",
    "meta.lang.s": "English, Spanish",
    "meta.lic.k": "License",
    "meta.lic.v": "UAV0 & UAV1",
    "meta.lic.s": "Licensed drone pilot",

    "skills.idx": "02",
    "skills.title": "How I build",
    "skills.m.title": "Mobile Development",
    "skills.ai.title": "AI & Machine Learning",
    "skills.tools.title": "Other Tools",

    "ach.idx": "03",
    "ach.title": "Wins",
    "ach.1.rank": "1st in World",
    "ach.1.title": "RoboChallenge AirRace",
    "ach.1.desc": "Romania, 2022 — Took first place globally with autonomous drone software that follows dashed lines between two poles.",
    "ach.2.rank": "Turkey 2nd",
    "ach.2.title": "Teknofest UAV Competition",
    "ach.2.desc": "Placed 2nd in Turkey at the Inter-High School Unmanned Aerial Vehicles competition.",
    "ach.3.rank": "Turkey 3rd",
    "ach.3.title": "TÜBİTAK — Smart Child Lock",
    "ach.3.desc": "Won 3rd place in Turkey at TÜBİTAK with an automotive child-lock control project.",

    "proj.idx": "04",
    "proj.title": "Projects",
    "proj.featured.tag": "Featured product",
    "proj.featured.name": "Looked",
    "proj.featured.desc": "An app that turns AI into a personal style consultant. Upload a photo for instant outfit feedback, add your wardrobe, and explore outfits the AI — or you — created. Data stays safe with Firebase and Google Sign-In.",
    "proj.featured.cta": "View on Google Play",
    "proj.featured.cta.ios": "Get on App Store",
    "proj.live": "Live",
    "proj.status.progress": "In progress",
    "proj.status.done": "Completed",

    "proj.1.name": "Smart Academic Advisor",
    "proj.1.desc": "An AI-powered advisor for university students — queries the database, analyzes documents, and openly admits when it doesn't know. My graduation project.",
    "proj.1.type": "AI Assistant",
    "proj.2.name": "Poco Loco",
    "proj.2.desc": "An e-commerce site I designed and built from scratch for a bag brand built around freedom of expression — a full storefront with a product catalog, cart, wishlist and login.",
    "proj.2.type": "Web · E-Commerce",
    "proj.3.name": "Optura",
    "proj.3.desc": "An app that recognizes products from grocery receipts to track your pantry automatically; it predicts expiration dates and warns you before items start to spoil. Currently in development.",
    "proj.3.type": "Mobile · AI",

    "path.idx": "05",
    "path.title": "Experience",
    "path.1.kind": "Work",
    "path.1.role": "Freelance Web & Mobile Developer",
    "path.1.org": "Independent",
    "path.1.when": "2025 — Now",
    "path.1.desc": "Building web and mobile projects end-to-end — from UI/UX design to backend integration.",
    "path.2.kind": "Product",
    "path.2.role": "Developer — Looked",
    "path.2.org": "Personal product",
    "path.2.when": "2026 — Now",
    "path.2.desc": "Took an AI-powered style assistant from idea to a live Google Play release.",
    "path.3.kind": "Competition",
    "path.3.role": "Autonomous Drone Software Team",
    "path.3.org": "International & TÜBİTAK",
    "path.3.when": "2019 — 2022",
    "path.3.desc": "Built autonomous flight algorithms; won 1st in the world in Romania, 2nd in Turkey at Teknofest, and a TÜBİTAK placement.",
    "contact.idx": "06",
    "contact.title": "Drop me a line",
    "contact.lead": "Got an idea, or a freelance project in mind? Email gets the fastest reply.",
    "social.email": "Email",
    "social.email.copy": "Copied!",
    "social.linkedin": "LinkedIn",
    "social.github": "GitHub",
    "form.name": "Name",
    "form.email": "Email",
    "form.msg": "Message",
    "form.name.ph": "Your name",
    "form.email.ph": "you@example.com",
    "form.msg.ph": "Tell me about your project…",
    "form.send": "Send message",
    "form.sending": "Sending…",
    "form.ok.title": "Thank you!",
    "form.ok.body": "Your message has been received — I'll get back to you soon.",
    "form.error": "Something went wrong, please try again later.",

    "mf.line1": "4 apps.",
    "mf.line2": "1 world championship.",
    "mf.line3": "Countless commits.",
    "mf.coda": "It all started with one question.",
    "foot.tag": "Made with coffee, from Türkiye.",
    "foot.top": "Back to top"
  }
};
